---
- hosts: localhost
  gather_facts: yes

  roles:
      - { role: kurron.docker-host, docker_engine_storage_driver: overlay }

  post_tasks:
      - name: Clear Out Downloads
        shell: "rm -f {{ansible_user_dir}}/Downloads/*.*"
      - name: Clear Out Guest Additions
        shell: "rm -f {{ansible_user_dir}}/*.iso"
      - name: Erase downloaded archive files
        shell: "yum clean all"
